updated compile_pyinstaller

diff --git a/python-projects/compile_pyinstaller b/python-projects/compile_pyinstaller
--- a/python-projects/compile_pyinstaller
+++ b/python-projects/compile_pyinstaller
@@ -1,42 +1,50 @@
 #! /bin/bash
 
 ##############################################################################
-# FILE: (bash script) compile_pyinstaller
-# AUTHOR: R-Logik, Deutschland. https://github.com/RLogik/phpytex
+# FILE: (bash script) compile_pytinstaller
+# AUTHOR: R-Logik, Deutschland. https://github.com/RLogik/bash-scripts
 # CREATED: 28.07.2020
+# LAST CHANGED: 30.07.2020
+# VERSION: 1·0·1
 # DESCRIPTION:
-#   A script which allows simple, reliable compilation of a python project
-#   via the pyinstaller compiler. It deals with all the versioning pitfalls
-#   by creating a virtual python environment and working locally with this.
-# LAST CHANGED: 28.07.2020
-# VERSION: 1·0·0
+#    A script which allows simple, reliable compilation of a python project
+#    via the pyinstaller compiler. It deals with all the versioning pitfalls
+#    by creating a virtual python environment and working locally with this.
 # NOTES:
 #
-#     Installation:
-#     ~~~~~~~~~~~~~
-#     1. modify the first 2 lines of this script if necessary.
-#     2. place this in a folder, which is in the PATH variable (or extend this)
-#     3. you may need to run
+#    Installation:
+#    ~~~~~~~~~~~~~
+#    1. modify the first 2 lines of this script if necessary.
+#    2. place this in a folder, which is in the PATH variable (or extend this)
+#    3. you may need to run
 #            dos2unix <name of this script>
-#        beforehand. Then run
+#       beforehand. Then run
 #            sudo chmod +x <name of this script>
-#        in bash. The command is now available everywhere on your system.
+#       in bash. The command is now available everywhere on your system.
 #
-#     Usage:
-#     ~~~~~~~~~~~~~
+#    Usage:
+#    ~~~~~~~~~~~~~
 #
-#     compile_pytinstaller
-#         [required] python-path=<path to suitable python distribution>
-#         [required] app-name=<desired name of programme>
-#         [required] setup-file=<name of python setup file>
-#         [optional] icon=<relative location of a .ico file>
+#    compile_pytinstaller
+#        [required] python-path=<path to suitable python distribution>
+#        [required] app-name=<desired name of programme>
+#        [required] setup-file=<name of python setup file>
+#        [optional] --icon=<relative location of a .ico file>
+#        [optional] --specpath=<path where .spec will be placed>
+#            DEFAULT = .
+#        [optional, multiple]
+#                   --add-data <path1:path2>
+#                   --add-data <path1:path2>
+#                   ...
+#                   --add-data <path1:path2>
+#            path1 relative to specpath
+#            path2 relative to build folder
 #
 #    - you can/should use "$(python_for_pyinstaller --which)" for the pytho-path argument.
 #    - In your setup file use pyinstaller_setuptools.
 #    Consult https://pypi.org/project/pyinstaller-setuptools/
 #
 ##############################################################################
-
 
 SCRIPTARGS="$@";
 
@@ -89,12 +97,17 @@ function has_arg() {
 }
 ################################################################
 
+PYTHONPATH="$(get_kwarg "$SCRIPTARGS" "python-path" "")";
 NAMEOFAPP="$(get_kwarg "$SCRIPTARGS" "app-name" "")";
 SETUPFILE="$(get_kwarg "$SCRIPTARGS" "setup-file" "")";
-ICONIMAGE="$(get_kwarg "$SCRIPTARGS" "icon" "")";
-PYTHONPATH="$(get_kwarg "$SCRIPTARGS" "python-path" "")";
+ICONIMAGE="$(get_kwarg "$SCRIPTARGS" "--icon" "")";
+SPECPATH="$(get_kwarg "$SCRIPTARGS" "--specpath" ".")";
 ADDDATA="$(get_all_kwargs "$SCRIPTARGS" "--add-data " "--add-data " true)";
-SPECPATH="$(get_kwarg "$SCRIPTARGS" "spec-path" "logs")";
+
+if [[ "$PYTHONPATH" == "" ]]; then
+    echo -e "\033[1;91mERROR\033[0m! Need \033[1mpython-path\033[0m argument.";
+    exit 1;
+fi
 
 if [[ "$NAMEOFAPP" == "" ]]; then
     echo -e "\033[1;91mERROR\033[0m! Need \033[1mapp-name\033[0m argument.";
@@ -103,11 +116,6 @@ fi
 
 if [[ "$SETUPFILE" == "" ]]; then
     echo -e "\033[1;91mERROR\033[0m! Need \033[1msetup-file\033[0m argument.";
-    exit 1;
-fi
-
-if [[ "$PYTHONPATH" == "" ]]; then
-    echo -e "\033[1;91mERROR\033[0m! Need \033[1mpython-path\033[0m argument.";
     exit 1;
 fi
 
@@ -124,7 +132,7 @@ echo -e "  \033[4;34m2. Switch To Virtual Python Environment:\033[0m";
 source env/bin/activate;
 vpython_path="$(which python3)";
 echo -e "  Path to python3: \033[1;96m$vpython_path\033[0m.";
-echo -e "  Version used:    \033[1;91m$(python3 -V 2>&1)\033[0m.";
+echo -e "  Version used:    \033[1;92m$(python3 -V 2>&1)\033[0m.";
 echo -e "";
 
 ################################################################
@@ -150,13 +158,13 @@ echo -e "  \033[4;34m2. Install:\033[0m";
 python3 $SETUPFILE install
 echo -e "";
 echo -e "  \033[4;34m3. Create executable:\033[0m";
-python3 $SETUPFILE pyinstaller -- \
+python3 -m PyInstaller $SETUPFILE \
+    --onefile \
     --paths "$paths" \
-    --onefile --name="$NAMEOFAPP" \
+    --name="$NAMEOFAPP" \
     --icon="$ICONIMAGE" \
     --specpath="$SPECPATH" \
     $ADDDATA;
-
 
 ################################################################
 # GARBAGE ENTFERNUNG
